var paisOperator = angular.module("paisOperator", ['ngRoute', 'ngCookies', 
	'angularjs-dropdown-multiselect', 'angularCharts', 
	'ngMagnify', 'nvd3', 'ngSanitize','pascalprecht.translate', 'ui.bootstrap', 'ServerService', 'cgBusy', 'ngFileUpload', 'LocalStorageModule']);


paisOperator.config(function($sceDelegateProvider) {
  $sceDelegateProvider.resourceUrlWhitelist([
    // Allow same origin resource loads.
    'self',
    // Allow loading from our assets domain.  Notice the difference between * and **.
    'http://srv*.assets.example.com/**'
  ]);
});

paisOperator.run(function($rootScope, $translate) {
        $rootScope.translate = function(lang) {
			     $translate.use(lang);
        };
        $rootScope.getLanguage = function () {
          return $translate.use();
        };
});



paisOperator.config(function($translateProvider) {
    $translateProvider.useSanitizeValueStrategy(null);
    $translateProvider.translations('en', {
      NEW_ORDER: 'New order',
      MY_ORDERS: 'My orders',
      MY_RESULTS: 'Images and sensors',
      MY_PROFILE: 'My profile',
      EXIT : 'Exit',
      ORDER : 'Order',
      NAME_ORDER : 'Order name',
      IMAGE_SETTINGS : 'Image settings',
      NO_TERITORIES: 'Number of selected teritorries:',
      SURFACE: 'Selected surface in ha:',
      IMAGE_TYPES: 'Image types:',
      IMAGE_START: 'Start of image taking:',
      IMAGE_END: 'End of image taking:',
      IMAGE_FREQ: 'Image frequency:',
      SENSOR_SETTINGS: 'Sensor settings',
      NO_SENSORS: 'Number of selected sensors',
	  SEVEN_DAYS: '7 days',
	  FIFTEEN_DAYS: '15 days',
	  MONTH: '30 days',
	  TWO_MONTHS: '60 days',
	  AGAIN: 'PONOVO',
	  SENSOR: 'Sensor',
    PASSWORD: 'PASSWORD',
    NAME: 'NAME',
    ADDRESS: 'ADDRESS',
    POST_CODE: 'POST CODE',
    CITY: 'CITY',
    PHONE: 'PHONE',
    SENSOR_STATION: 'Sensor Station',
    DOB: 'DATE OF REGISTRATION',
    SAVE: 'SAVE',
    EMAIL: 'E-MAIL',
    MY_DATA: 'My profile',
    RECORDING: 'Recording',
    ORDERS: 'Orders',
    IMAGES: 'Images',
    IMAGE_NAME: 'Name',
    IMAGE_TYPE: 'Type',
    IMAGE_TIME: 'Date',
    OPEN: 'Open',
    SENSORS: 'Sensors',
    FROM: 'From',
    TO: 'To',
    SENSOR_ID: 'Sensor id',
    REGISTER: 'Create account',
    LOGIN: 'Log in',
    LOGIN_MAIL: 'E-mail',
    LOGIN_PASSWORD : 'Password',
    ESTIMATE : 'ESTIMATE',
    DETAILS : 'Details',
    PERSONAL_ACCOUNT: 'Personal account',
    COMPANY_ACCOUNT: 'Company/Community account',
    ACCOUNT_TYPE: 'ACCOUNT TYPE',
    SURNAME: 'SURNAME',
    MAIL_EXAMPLE: 'my@mail.com',
    PROFILE_CHANGE: 'Profile data change',
    PROFILE_CHANGE_SUCCESS: 'Profile information successfully updated.',
    PROFILE_CHANGE_FAIL: 'Profile information update failed! Please contact our support team.',
    CLOSE: 'Close',
    USERNAME: 'USERNAME',
    COUNTRY: 'COUNTRY',
    LOGIN_USERNAME: 'Username',
    REGISTER_SUCCESS : 'Registration process completed successfully. You will receive mail with activation link shortly.',
    REGISTER_ERROR : 'There was an error with registration procedure. Try again later or contant our support team.',
    REGISTER_TITLE : 'REGISTRATION',
    BACK_TO_LOGIN: 'Back to login',
    BACKEND_ERROR: 'Error in loading data. Try again later or contact our support team.',
    CREATE: 'REGISTER',
    NO_ORDERS: 'No orders assigned to your company',
    ACTIVE: 'ACTIVE',
    INACTIVE: 'NOT ACTIVE',
    FINISHED_INFO: 'This order is finished.',
    LOADING: 'LOADING...',
    CREATED_AT: 'Created',
    DESCRIPTION: 'Description',
    ACTIVE_SENSORS: 'Activated',
    INACTIVE_SENSORS: 'Not activated',
    INFORMATION: 'Informations',
    CHOOSEN_SERVICES: 'Selected services:',
    CHOOSEN_NO_T: 'Number of selected territories ',
    CHOOSEN_NO_T_SURFACE: 'With a total surface of',
    CHOOSEN_NO_SENSORS: 'Placed sensors',
    CHOOSEN_EVALUATE: 'Evaluation',
    APPROX_VALUE: 'Approximate value of services is',
    ESTIMATE_ALERT: 'NOTE: Estimated value is calculated only approximately and may vary from the exact prices. After the order confirmation you will be contacted by our team who will familiarize you with the accurate price, method and schedule of payments.',
    LEGAL_NOTE: 'Legal note',
    ACCEPT_TOS: 'By ordering selected services, you accept Terms of Service.',    
    CONFIRM_ORDER: 'Confirm order',
    CANCEL_ORDER: 'Back',
    ORDER_SUCCESS: 'Order successfully placed. You will be contacted be our staff according to your profile data.',
    ORDER_FAILED: 'Error occured while placing and order. Please try again later or contact our support team.',
    EVALUATE_CLICK: 'Click here to estimate',
    SENSOR_DESCRIPTION: 'Sensor description',
    ERROR_GEN: 'ERROR',
    ERROR_GEN_DET: 'Error in communication occured. Please try again later or contact our support team.',
    WARN_NAME: 'Order name must contain at least 3 alpha-numerical characters.',
    WARN_IMG_TYPES: 'At least one image type must be selected.',
    WARNING_GEN : 'WARNING',
    WARNING_IMG_DESC: 'Order description cannot have more than 100 characters.',
    ERROR_LOGIN : 'Please check your username and try again',
    TIME_FILTER: 'Time filter',
    BACK: 'Back',
    SENSOR: 'Sensor ID',
    TER: 'Territory ID',
    TER_SUR: 'Surface',
    UPLOAD_IMAGES: 'Upload images',
    DOWNLOAD_SEN_CONF: 'Download sensor configuration',
    DOWNLOAD_DRON_CONF: 'Download dron configuration',
    SENSORS: 'Sensors',
    SENSOR_STATIONS: 'Sensor stations',
    SENSOR_DATA: 'Sensor data',
    DRON_DATA: 'Dron images data',
    SENSOR_DET : 'Sensor details',
    DESC_ADD : 'Description/Additional remarks:',
    TYPE: 'Type:',
    UOM: 'UOM:',
    LAT: 'Latitude',
    LONGITUDE: 'Longitude',
    IMAGES: 'Images',
    INFO: 'Information',
    SENSOR_ACT : "Sensor activated",
    SUCC : "Success",
    SUCC_ALL_IMG : "All images uploaded successfully!",
    UPLOAD : "Upload",
    UPLOAD_DRON : "Select Dron images",
    UPLOAD_DRON_TTL : "Upload image file",
    UPLOAD_CONF_TTL : "Upload config file",
    UPLOAD_CONF : "Select Configuration File",
    FILE: "File",
    PRG: "Progress",
    UPLOADED: "Uploaded images",
    UPLOADED_NAME: "Name",
    UPLOADED_DATE: "Date",
    UPLOADED_SIZE: "Size [MB]",
    CHANGES_SAVED: "Changes are successfully saved",
    COMPANY: "OPERATOR COMPANY",
    SERVICE_TIME: "Service time",
    SERVICE_TIME_FROM: "From",
    SERVICE_TIME_TO: "To",
    SERVICE_TIME_FREQ: "Image frequency",
    SERVICE_TIME_IMAGES: "Image types",
    COMMAND: "Download configuration & Upload results",
    ORDERS_ASSIGNED: "Orders assigned to ",
    LOADING_ORDER_DETAILS: "Loading order details...",
    ORDER_DESC: "Description/Additional remarks",
    ORDER_BY: "Ordered By:",
    TER_NAME: "Territory",
    ACT_SENS: "Active",
    INACT_SENS: "Not active",
    UPLOAD_OVERVIEW: "Upload overview",
    UPLOAD_FILE_NAME_ERROR : "Files are not named correctly. File that failed",
    UPLOAD_DG_ERROR: "Wrong number of downgraded images.",
    UPLOAD_CONFIG_FILE_TITLE: "Image information config file:",
    UPLOAD_NOT_KML : "Config file is not in the .kml format!",
    LARGE_IMAGES: 'Large images:',
    CONTINUE : 'Continue',
    CANCEL: 'Cancel',
    INSTRUCTIONS: 'Instructions',
    ONLY_KMLS: 'Only for .kml files',
    ONLY_LARGE_IMAGES: 'For images larger than 5mb',
    ONLY_IMAGES : 'For images bellow 5mb',
    UPLOAD_LG_IMAGES: 'Upload large pictures',
    INSTR_MANUAL: 'Instruction manual',
    MANUAL_READ_ACCEPTED: 'Manual read and accepted',
    MANUAL_NOT_ACCEPTED : 'Manual not read and accepted',
    UPLOADED_KMLS : "Uploaded flight plans (KMLs)",
    IMAGE_SIZE : "Image size",
    CHANGE_PASSWORD : "Change password",
    DELETE_IMGS: "Delete",
    DELETE_ALL: "Delete all",
    DELETE_Q : "Are you sure you want to delete all images and KML files from this polygon?",
    DELETE_BTN: "Delete all images and KML files",
    ALL_ON_MAP: "Show all on map",
    OLD_PASS: 'Old password',
    NEW_PASS: 'New password',
    NEW_PASS_REP : 'Repeat new password'
    })
    .translations('rs', {
      NEW_ORDER: 'Nova porudžbina',
      MY_ORDERS: 'Moje porudžbine',
      MY_RESULTS: 'Snimanja i senzori',
      MY_PROFILE: 'Moji podaci',
      EXIT : 'Izlaz',
      ORDER : 'Narudžbina',
      NAME_ORDER : 'Ime narudžbine',
      IMAGE_SETTINGS : 'Podešavanje snimanja',
      NO_TERITORIES: 'Broj obeleženih teritorija:',
      SURFACE: 'Obeležena površina u ha:',
      IMAGE_TYPES: 'Tipovi snimanja:',
      IMAGE_START: 'Početak snimanja:',
      IMAGE_END: 'Kraj snimanja:',
      IMAGE_FREQ: 'Frekvencija snimanja:',
      SENSOR_SETTINGS: 'Podešavanja senzora',
      NO_SENSORS: 'Broj obeleženih senzora',
	  SEVEN_DAYS: '7 dana',
	  FIFTEEN_DAYS: '15 dana',
	  MONTH: '30 dana',
	  TWO_MONTHS: '60 dana',
	  AGAIN: 'PONOVO',
	  SENSOR: 'Senzor',
	  PASSWORD: 'LOZINKA',
	  NAME: 'IME',
	  ADDRESS: 'ADRESA',
	  POST_CODE: 'POŠTANSKI BROJ',
	  CITY: 'OPŠTINA',
	  PHONE: 'KONTAKT TELEFON',
      SENSOR_STATION: 'Senzorska stanica',
	  DOB: 'DATUM REGISTRACIJE',
	  SAVE: 'SAČUVAJ',
    EMAIL: 'MEJL ADRESA',
	  MY_DATA: 'Moji podaci',
	  RECORDING: 'Snimanje',
	  ORDERS: 'Narudžbine',
	  IMAGES: 'Slike',
	  IMAGE_NAME: 'Ime',
	  IMAGE_TYPE: 'Tip slike',
	  IMAGE_TIME: 'Vreme',
	  OPEN: 'Otvori',
	  SENSORS: 'Senzori',
	  FROM: 'Od',
	  TO: 'Do',
	  SENSOR_ID: 'Senzor id',
    REGISTER: 'Napravi novi nalog',
    LOGIN: 'Ulaz',
    LOGIN_MAIL: 'Mejl adresa',
    LOGIN_PASSWORD : 'Lozinka',
    ESTIMATE : 'Proceni',
    DETAILS : 'Detalji',
    PERSONAL_ACCOUNT: 'Fizičko lice',
    COMPANY_ACCOUNT: 'Pravno lice (kompanija ili udruženje)',
    ACCOUNT_TYPE: 'TIP NALOGA',
    SURNAME: 'PREZIME',
    MAIL_EXAMPLE: 'moj@mejl.rs',
    PROFILE_CHANGE: 'Promena podataka',
    PROFILE_CHANGE_SUCCESS: 'Promena podataka je uspešno obavljena.',
    PROFILE_CHANGE_FAIL: 'Promena podataka nije uspela! Molimo kontaktirajte našu podršku.',
    CLOSE: 'Zatvori',
    USERNAME: 'KORISNIČKO IME',
    COUNTRY: 'DRŽAVA',
    LOGIN_USERNAME: 'Korisničko ime',
    REGISTER_SUCCESS : 'Registracija uspešno obavljena. Uskoro ćete na unetu mejl adresu dobiti mejl sa aktivacionim linkom. Ukoliko imate problema sa aktiviranjem naloga, kontaktirajte našu podršku.',
    REGISTER_ERROR : 'Došlo je do greške u procesu registracije. Pokušajte ponovo kasnije ili kontaktirajte našu podršku.',
    REGISTER_TITLE : 'REGISTRACIJA',
    BACK_TO_LOGIN: 'Nazad na prijavu',
    BACKEND_ERROR: 'Greška pri učitavanju podataka. Pokušajte kasnije ili kontaktirajte našu podršku.',
    CREATE: 'REGISTRACIJA',
    NO_ORDERS: 'Nemate nijednu porudžbinu dodeljenu Vašoj operatorskoj kompaniji',
    ACTIVE: 'AKTIVNA',
    INACTIVE: 'NIJE AKTIVNA',
    CANCELED: 'OTKAZANA',
    FINISHED: 'FINISHED',
    FINISHED_INFO: 'Ova narudžbina je završena',
    LOADING: 'UČITAVANJE...',
    CREATED_AT: 'Napravljena',
    DESCRIPTION: 'Opis narudžbine',
    ACTIVE_SENSORS: 'Aktiviranih',
    INACTIVE_SENSORS: 'Neaktiviranih',
    INFORMATION: 'Informacija',
    CHOOSEN_SERVICES: 'Odabrane usluge:',
    CHOOSEN_NO_T: 'Broj obeleženih teritorija',
    CHOOSEN_NO_T_SURFACE: 'Ukupne površine',
    CHOOSEN_NO_SENSORS: 'Broj senzora',
    CHOOSEN_EVALUATE: 'Procena vrednosti:',
    APPROX_VALUE: 'Približna vrednost obeleženih usluga je',
    ESTIMATE_ALERT: 'NAPOMENA: Procenjena vrednost je samo približno izračunata i može varirati od tačne cene. Po potvrdi narudžbine bićete kontaktirani od strane našeg tima koji će vas upoznati sa tačnom cenom, načinom i dinamikom plaćanja.',
    LEGAL_NOTE: 'Pravne informacije',
    ACCEPT_TOS: 'Naručivanjem obeleženih usluga prihvatam uslove korišćenja.',
    CONFIRM_ORDER: 'Potvrdi narudžbinu',
    CANCEL_ORDER: 'Nazad',
    ORDER_SUCCESS: 'Narudžbina je uspešno poslata. Očekujte da budete kontaktirani preko kontakt brojeva koji se nalaze u vašem profilu.',
    ORDER_FAILED: 'Došlo je do greške prilikom slanja narudžbine. Pokušajte kasnije ili kontaktirajte našu podršku.',
    EVALUATE_CLICK: 'Proceni narudžbinu',
    SENSOR_DESCRIPTION: 'Opis senzora',
    ERROR_GEN: 'GREŠKA',
    ERROR_GEN_DET: 'Došlo je do greške u komunikaciji. Pokušajte kasnije ili kontaktirajte našu podršku.',
    WARN_NAME: 'Ime narudžbine mora sadržati minimalno 3 karaktera.',
    WARN_IMG_TYPES: 'Minimalno jedan tip snimanja mora biti odabran.',
    WARNING_GEN : 'UPOZORENJE',
    WARNING_IMG_DESC: 'Opis narudžbine može imati maksimalno 100 karaktera.',
    ERROR_LOGIN : 'Proverite podatke i pokušajte ponovo',
    TIME_FILTER: 'Vremenski filter',
    BACK: 'Nazad',
    SENSOR: 'Senzor ID ',
    TER: 'Plac ID ',
    TER_SUR: 'Površina',
    UPLOAD_IMAGES: 'Postavi slike',
    DOWNLOAD_SEN_CONF: 'Dobavi konfiguraciju senzora',
    DOWNLOAD_DRON_CONF: 'Dobavi konfiguraciju drona',
    SENSORS: 'Senzori',
    SENSOR_STATIONS: 'Senzorske stanice',
    SENSOR_DATA: 'Podaci senzora',
    DRON_DATA: 'Podaci slika sa drona',
    SENSOR_DET : 'Detalji senzora',
    DESC_ADD : 'Opis/dodatni zahtevi:',
    TYPE: 'Tip:',
    UOM: 'Jedinica mere:',
    LAT: 'Širina',
    LONGITUDE: 'Dužina',
    IMAGES: 'Slike',
    INFO: 'Informacija',
    SENSOR_ACT : "Senzor aktiviran",
    SUCC : "Uspešno završeno",
    SUCC_ALL_IMG : "Sve slike su uspešno poslate!",
    UPLOAD : "Pošalji",
    UPLOAD_DRON : "Izaberi slike sa snimanja dronom",
    UPLOAD_DRON_TTL : "Pošalji slike sa drona",
    UPLOAD_CONF_TTL : "Pošalji konfiguracioni fajl",
    UPLOAD_CONF : "Izaberi konfiguracioni fajl",
    FILE: "Fajl",
    PRG: "Završeno",
    UPLOADED: "Poslate slike",
    UPLOADED_NAME: "Ime",
    UPLOADED_DATE: "Datum",
    UPLOADED_SIZE: "Veličina [MB]",
    CHANGES_SAVED: "Izmene sačuvane",
    COMPANY: "OPERATORSKA KOMPANIJA",
    SERVICE_TIME: "Period usluge",
    SERVICE_TIME_FROM: "Od",
    SERVICE_TIME_TO: "Do",
    SERVICE_TIME_FREQ: "Frekvencija snimanja",
    SERVICE_TIME_IMAGES: "Tipovi snimanja",
    COMMAND: "Dobavi konfiguraciju & Pošalji rezultate",
    ORDERS_ASSIGNED: "Narudžbine dodeljenje ",
    LOADING_ORDER_DETAILS: "Učitavanje detalja narudžbine...",
    ORDER_DESC: "Opis/Dodatne napomene",
    ORDER_BY: "Naručeno od:",
    TER_NAME: "Plac/Teritorija",
    ACT_SENS: "Aktiviran",
    INACT_SENS: "Nije aktiviran",
    UPLOAD_OVERVIEW: "Pregled",
    UPLOAD_FILE_NAME_ERROR : "Fajlovi nisu dobro nazvani. Fajl koji je pao validaciju - ",
    UPLOAD_DG_ERROR: "Pogrešan broj slika slabijeg formata.",
    UPLOAD_CONFIG_FILE_TITLE: "Konfiguracioni fajl leta:",
    UPLOAD_NOT_KML : "Konfiguracioni fajl nije u .kml formatu!",
    LARGE_IMAGES: 'Velike slike:',
    CONTINUE : 'Nastavi',
    CANCEL: 'Odustani',
    INSTRUCTIONS: 'Uputstva',
    ONLY_KMLS: 'Samo za .kml fajlove',
    ONLY_LARGE_IMAGES: 'Za slike veće od 5mb',
    ONLY_IMAGES : 'Za slike ispod 5mb',
    UPLOAD_LG_IMAGES: 'Pošalji velike slike',
    INSTR_MANUAL: 'Uputstvo',
    MANUAL_READ_ACCEPTED: 'Uputstvo pročitano i prihvaćeno',
    MANUAL_NOT_ACCEPTED : 'Uputstvo nije prihvaćeno',
    UPLOADED_KMLS : "Poslati planovi leta (.kml)",
    IMAGE_SIZE : "Veličina slike",
    CHANGE_PASSWORD : "Promeni lozinku",
    DELETE_IMGS: "Obriši",
    DELETE_ALL: "Obriši sve",
    DELETE_Q : "Da li ste sigurni da želite da obrišete sve slike i KML datoteke vezane za ovaj poligon sa servera?",
    DELETE_BTN: "Izbriši sve slike i KML-ove",
    ALL_ON_MAP: "Prikaži sve na mapi",
    OLD_PASS: 'Stara lozinka',
    NEW_PASS: 'Nova lozinka',
    NEW_PASS_REP : 'Ponovi novu lozinku'
    });
    $translateProvider.preferredLanguage('en');
});

paisOperator.filter('trusted', ['$sce', function ($sce) {
    return function(url) {
    	console.log("filter called " + url);
        return $sce.trustAsResourceUrl(url);
    };
}]);

paisOperator.directive("mySrc", function() {
    return {
      link: function(scope, element, attrs) {
        var img, loadImage;
        img = null;

        loadImage = function() {

          element[0].src = "/img/spinner.gif";

          img = new Image();
          img.src = attrs.mySrc;

          img.onload = function() {
            element[0].src = attrs.mySrc;
          };
        };

        scope.$watch((function() {
          return attrs.mySrc;
        }), function(newVal, oldVal) {
          if (oldVal !== newVal) {
            loadImage();
          }
        });
      }
    };
  });